export const API_CONSTANTS = {
    SINGNUP: "auth/create-user",
    LOGIN: "auth/login",
    VERIFY_TOKEN: "auth/verify-token",
    FORGOT_PASSWORD: "auth/forgot-password",
    RESET_PASSWORD: "auth/reset-password",
    LOGOUT: "auth/logout",
    ADD_CATEGORY_DETAILS: "category/create",
    UPDATE_CATEGORY_DETAILS: "",
    GET_ALL_CATEGORY_DETAILS: "category/list",
    GET_ALL_CATEGORY_DETAILS_BY_CATEGORY_ID: "admin/getCategoryByCategoryId",
    DELETE_CATEGORY_DETAILS: "category/delete",
    GET_CATEGORY_DETAILS_BY_ID: "admin/getCategoryDtlsById",
    ADD_PRODUCT_DETAILS: "admin/addProductDetails",
    UPDATE_PRODUCT_DETAILS: "admin/addProductDetails",
    GET_ALL_PRODUCT_DETAILS: "product/list",
    GET_ALL_PRODUCT_DETAILS_BY_PRODUCT_ID: "admin/getProductDtlsByProductId",
    DELETE_PRODUCT_DETAILS: "product/delete",
}