export const API_CONSTANTS = {
    SINGNUP: "admin/userRegistration",
    LOGIN: "admin/login",
    ADD_UPDATE_SHOP_DETAILS: "admin/addShopDetails",
    GET_ALL_SHOP_DETAILS: "admin/getAllShopDtlsByUserId", 
    GET_ALL_SHOP_DETAILS_BY_SHOP_ID: "admin/getShopDetailsByShopId",
    DELETE_SHOP_DETAILS: "admin/deleteShopDtlsById",
    ADD_UPDATE_CATEGORY_DETAILS: "admin/addEditCategoryDtls",
    GET_ALL_CATEGORY_DETAILS: "admin/getAllCategoryDtls",
    GET_ALL_CATEGORY_DETAILS_BY_CATEGORY_ID: "admin/getCategoryByCategoryId",
    DELETE_CATEGORY_DETAILS: "admin/deleteCategoryDtls",
    GET_CATEGORY_DETAILS_BY_ID: "admin/getCategoryDtlsById",
    ADD_UPDATE_PRODUCT_DETAILS: "admin/addProductDetails",
    GET_ALL_PRODUCT_DETAILS: "admin/getAllProducts",
    GET_ALL_PRODUCT_DETAILS_BY_PRODUCT_ID: "admin/getProductDtlsByProductId",
}