export const ROUTES_CONSTANTS = {
    // User based routes
    HOME: "/",
    VIEW_CART: "/view-cart",
    VIEW_BLOG_DESCRIPTION: "/view-blog",
    VIEW_COLLECTION_DESCRIPTION: "/collections",
    
    // Admin based routes
    LOGIN: "/login",
    SIGNUP: "/signup",
    DASHBOARD: "/dashboard",
    PRODUCTS: "/dashboard/products",
    ORDERS: "/dashboard/orders",
    INVENTORY: "/dashboard/inventories",
    CATEGORIES: "/dashboard/categories",
    SUB_CATEGORIES: "/dashboard/sub-categories",
    COUPONS: "/dashboard/coupons",
    REPORTS: "/dashboard/reports",
    USERS: "/dashboard/users",
    ADDRESSES: "/dashboard/addresses",
    DISCOUNT: "/dashboard/discounts",
    REVIEWS: "/dashboard/reviews",
    BLOGS: "/dashboard/blogs",
    FEST: "/dashboard/fests",
    CREATE_CATEGORY: "/dashboard/create-category",
    CREATE_SUB_CATEGORY: "/dashboard/create-sub-category",
    CREATE_PRODUCT: "/dashboard/create-product",
    CREATE_INVENTORY: "/dashboard/create-inventory",
    CREATE_ORDER: "/dashboard/create-order",
    CREATE_COUPON: "/dashboard/create-coupon",
    CREATE_REPORT: "/dashboard/create-report",
    CREATE_USER: "/dashboard/create-user",
    CREATE_DISCOUNT: "/dashboard/create-discount",
    CREATE_ADDRESESS: "/dashboard/create-addresess",
    CREATE_BLOG: "/dashboard/create-blog",
    CREATE_FEST_PRODUCT: "/dashboard/create-fest-product",
    EDIT_CATEGORY: "/dashboard/edit-category",
    EDIT_SUB_CATEGORY: "/dashboard/edit-sub-category",
    EDIT_PRODUCT: "/dashboard/edit-product",
    EDIT_INVENTORY: "/dashboard/edit-inventory",
    EDIT_ORDER: "/dashboard/edit-order",
    EDIT_COUPON: "/dashboard/edit-coupon",
    EDIT_REPORT: "/dashboard/edit-report",
    EDIT_USER: "/dashboard/edit-user",
    EDIT_DISCOUNT: "/dashboard/edit-discount",
    EDIT_ADDRESESS: "/dashboard/edit-addresess",
    EDIT_BLOG: "/dashboard/edit-blog",
    EDIT_FEST_PRODUCT: "/dashboard/edit-fest-product"
}