export const ROUTES_CONSTANTS = {
    HOME: "/",
    LOGIN: "/login",
    SIGNUP: "/signup",
    DASHBOARD: "/dashboard",
    PRODUCTS: "/dashboard/products",
    ORDERS: "/dashboard/orders",
    INVENTORY: "/dashboard/inventories",
    CATEGORIES: "/dashboard/categories",
    SUB_CATEGORIES: "/dashboard/sub-categories",
    COUPONS: "/dashboard/coupons",
    REPORTS: "/dashboard/reports",
    USERS: "/dashboard/users",
    ADDRESSES: "/dashboard/addresses",
    DISCOUNT: "/dashboard/discounts",
    CREATE_CATEGORY: "/create-category",
    CREATE_SUB_CATEGORY: "/create-sub-category",
    CREATE_PRODUCT: "/create-product",
    CREATE_INVENTORY: "/create-inventory",
    CREATE_ORDER: "/create-order",
    CREATE_COUPON: "/create-coupon",
    CREATE_REPORT: "/create-report",
    CREATE_USER: "/create-user",
    CREATE_DISCOUNT: "/create-discount",
    CREATE_ADDRESESS: "/create-addresess",
    CREATE_USER: "/create-user"
}